// Copy the canonical Markdown into the docs tree, adding the front matter Docusaurus needs.
//
// The source of truth stays where it is: SPEC.md next to the code it specifies, package
// READMEs where PyPI renders them from. Copying at build time means the site cannot show a
// version of a document that the repository does not hold -- the same reason `check_drift.py`
// regenerates derived artifacts and fails when the tree is dirty.
//
// Run `npm run sync` before `build` and `start`; both do it automatically.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..", "..");
const DOCS = resolve(HERE, "..", "docs");

/** source in the repo -> [destination under docs/, title, sidebar_position] */
const SYNCED = [
  ["docs/SPEC.md", "reference/spec.md", "Specification", 1],
  ["docs/RELEASING.md", "reference/releasing.md", "Releasing", 2],
  ["CHANGELOG.md", "reference/changelog.md", "Changelog", 3],
  ["packages/prereg/README.md", "tools/prereg.md", "prereg", 1],
  ["packages/citations/README.md", "tools/citations.md", "citations", 2],
  ["packages/results/README.md", "tools/results.md", "results", 3],
  ["packages/repro/README.md", "tools/repro.md", "repro", 4],
];

const BANNER = (source) =>
  `{/* Generated by scripts/sync-docs.mjs from ${source}. Edit that file, not this one. */}`;

let written = 0;
for (const [source, target, title, position] of SYNCED) {
  const from = join(REPO, source);
  let body;
  try {
    body = readFileSync(from, "utf8");
  } catch {
    console.error(`  MISSING  ${source} — the docs site expects it to exist`);
    process.exitCode = 1;
    continue;
  }
  // Drop a leading H1: Docusaurus renders the title from front matter, and two would show.
  body = body.replace(/^#\s+.*\n+/, "");
  const front = [
    "---",
    `title: ${title}`,
    `sidebar_position: ${position}`,
    `description: ${title} — Reproducible Science`,
    "---",
    "",
    BANNER(source),
    "",
  ].join("\n");
  const out = join(DOCS, target);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, front + body);
  written += 1;
  console.log(`  ${source}  ->  docs/${target}`);
}
console.log(`\n  synced ${written}/${SYNCED.length}`);
